function [fitresult, gof] = poly8(dxi, dUoc)
%CREATEFIT(DXI,DUOC)
%  Create a fit.
%
%  Data for 'Uoc_krivulja' fit:
%      X Input : dxi
%      Y Output: dUoc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Nov-2022 23:43:32


%% Fit: 'Uoc_krivulja'.
[xData, yData] = prepareCurveData( dxi, dUoc );

% Set up fittype and options.
ft = fittype( 'poly8' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
%opts.Normalize = 'on';
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Uoc_krivulja' );
h = plot( fitresult, xData, yData );
legend( h, 'dUoc vs. dxi', 'Uoc_krivulja', 'Location', 'NorthEast' );
% Label axes
xlabel dxi
ylabel dUoc
grid on


